version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/postit/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      - BASE_HOST=http://
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postit.rule=Host(`postit.localhost`)"
      - "traefik.http.routers.postit.entrypoints=web"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - postit
  mongo:
    image: mongo:latest
    hostname: mongodb-server
    environment:
      MONGO_INITDB_DATABASE: postit-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ../../db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      default:

volumes:
  mongodb_data:

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik
