version: '3'

services:
  api:
    image: ghcr.io/tombowyerresearchproject/postit_api:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DATABASE_URL: postgres://tom:tom123@postgres_db:5432/postit_db
      VERIFICATION_URL: http://uacl/authorize
      NOTIFICATION_URL: http://notif/notification
      EMOTIVES_URL: http://emotives.net/
      HOST: 0.0.0.0
      PORT: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postit.rule=Host(`postit.emotives.net`)"
      - "traefik.http.routers.postit.tls=true"
      - "traefik.http.routers.postit.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - postit

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik