version: '3'

services:
  api:
    build:
      context: ../../.
      dockerfile: docker/postit/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../:/app
    environment:
      - BASE_HOST=http://
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postit.rule=Host(`postit.localhost`)"
      - "traefik.http.routers.postit.entrypoints=web"
      - "traefik.docker.network=traefik"
    restart: unless-stopped
    networks:
      traefik:
      default:
      emotives:
        aliases:
          - postit
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tom123
      POSTGRES_USER: tom
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ../../database/Initial/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      default:

volumes:
  postgres-data:

networks:
  emotives:
    external:
      name: emotives
  default:
  traefik:
    external:
      name: traefik
