version: '3'

services:
  postit:
    build:
      context: ../.
      dockerfile: docker/Dockerfile.prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postit.rule=Host(`postit.emotives.net`)"
      - "traefik.http.routers.postit.tls=true"
      - "traefik.http.routers.postit.tls.certresolver=letsencrypt"
    networks:
      traefik:
      postit:
  postit-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      postit:

volumes:
  mongodb_data_container:

networks:
  postit:
  traefik:
    external:
      name: traefik